FROM python:latest

WORKDIR /opt/project

RUN pip install --upgrade pip

COPY ./requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

COPY content .

CMD ["uvicorn", "app.main:app", "--reload", "--port", "8000", "--host", "localhost"]
